### PR TITLE
Change yawobject.position calls to the new cameraPosition()

### PR DESCRIPTION
**Pull request by nakedible**
Voxel-engine has gone forward, it now has a cameraPosition() call.

### CODE REVIEW

**Comment by shama** [comment]
Thanks!

**Comment by nakedible** [comment]
It would be cool if you could bump the package version and publish a new package, but no rush if you have other changes pending.

**Comment by nakedible** [comment]
Oh and voxel-engine dev dependency should be minimum 0.5.8.

**Comment by shama** [comment]
Yep will publish soon. In the process of updating all my voxel plugins to `voxel-engine@0.6.0`. ;)

**Comment by shama** [comment]
Published as `v0.1.2`. Thanks!

**Pull request merged**
